###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

like-a-boss-4.webserver:
  image: phpdockerio/nginx:latest
  container_name: like-a-boss-4.webserver
  volumes:
      - .:/var/www/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "83:80"
  links:
   - like-a-boss-4.phpfpm

like-a-boss-4.phpfpm:
  build: .
  dockerfile: ./docker/php-fpm/Dockerfile
  container_name: like-a-boss-4.phpfpm
  volumes:
    - .:/var/www/app
    - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini